version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres177
      POSTGRES_DB: pulse_v2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pulse_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: pulse@manush.tech
      PGADMIN_DEFAULT_PASSWORD: pulse@456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '4040:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:pgsql-server
    restart: always


volumes:
  pgdata:
  pgadmin-data:
